"""add fanzones table

Revision ID: 835cece4e486
Revises: c11ad614babe
Create Date: 2025-12-27 23:20:54.900778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '835cece4e486'
down_revision: Union[str, Sequence[str], None] = 'c11ad614babe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fanzones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('specific_location', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('is_official_caf_zone', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_fan_id', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_free', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('base_price_dh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('morocco_match_price_dh', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_notes', sa.Text(), nullable=True),
    sa.Column('venue_size_sqm', sa.Integer(), nullable=True),
    sa.Column('coverage_type', sa.String(), nullable=True),
    sa.Column('coverage_notes', sa.Text(), nullable=True),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('event_start_date', sa.Date(), nullable=True),
    sa.Column('event_end_date', sa.Date(), nullable=True),
    sa.Column('event_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('maps_place_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fanzones')),
    sa.UniqueConstraint('city', 'name', 'specific_location', 'is_official_caf_zone', name='uq_fanzones_city_name_location_official')
    )
    op.create_index(op.f('ix_fanzones_city'), 'fanzones', ['city'], unique=False)
    op.create_index('ix_fanzones_city_official', 'fanzones', ['city', 'is_official_caf_zone'], unique=False)
    op.create_index(op.f('ix_fanzones_is_official_caf_zone'), 'fanzones', ['is_official_caf_zone'], unique=False)
    op.create_index(op.f('ix_fanzones_name'), 'fanzones', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fanzones_name'), table_name='fanzones')
    op.drop_index(op.f('ix_fanzones_is_official_caf_zone'), table_name='fanzones')
    op.drop_index('ix_fanzones_city_official', table_name='fanzones')
    op.drop_index(op.f('ix_fanzones_city'), table_name='fanzones')
    op.drop_table('fanzones')
    # ### end Alembic commands ###
