"""initial_schema_static_and_schedule

Revision ID: c11ad614babe
Revises: 
Create Date: 2025-12-23 18:31:14.093784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c11ad614babe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stadiums'))
    )
    op.create_index(op.f('ix_stadiums_city'), 'stadiums', ['city'], unique=False)
    op.create_index(op.f('ix_stadiums_id'), 'stadiums', ['id'], unique=False)
    op.create_index(op.f('ix_stadiums_name'), 'stadiums', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('coach_name', sa.String(), nullable=True),
    sa.Column('flag_url', sa.String(), nullable=True),
    sa.Column('fifa_ranking', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams'))
    )
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=True)
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('validation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_changed', sa.String(), nullable=True),
    sa.Column('old_value', sa.String(), nullable=True),
    sa.Column('new_value', sa.String(), nullable=True),
    sa.Column('agent_reasoning', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_records'))
    )
    op.create_index('ix_validation_entity_type_id_checked_at', 'validation_records', ['entity_type', 'entity_id', 'checked_at'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.String(), nullable=True),
    sa.Column('team1_id', sa.Integer(), nullable=False),
    sa.Column('team2_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('kickoff_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_kickoff_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team1_score', sa.Integer(), nullable=True),
    sa.Column('team2_score', sa.Integer(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('validation_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], name=op.f('fk_matches_stadium_id_stadiums')),
    sa.ForeignKeyConstraint(['team1_id'], ['teams.id'], name=op.f('fk_matches_team1_id_teams')),
    sa.ForeignKeyConstraint(['team2_id'], ['teams.id'], name=op.f('fk_matches_team2_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_index(op.f('ix_matches_kickoff_time'), 'matches', ['kickoff_time'], unique=False)
    op.create_index(op.f('ix_matches_stadium_id'), 'matches', ['stadium_id'], unique=False)
    op.create_index(op.f('ix_matches_stage'), 'matches', ['stage'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_index(op.f('ix_matches_team1_id'), 'matches', ['team1_id'], unique=False)
    op.create_index(op.f('ix_matches_team2_id'), 'matches', ['team2_id'], unique=False)
    op.create_index(op.f('ix_matches_tournament_id'), 'matches', ['tournament_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_tournament_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team2_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team1_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_stage'), table_name='matches')
    op.drop_index(op.f('ix_matches_stadium_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_kickoff_time'), table_name='matches')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index('ix_validation_entity_type_id_checked_at', table_name='validation_records')
    op.drop_table('validation_records')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_stadiums_name'), table_name='stadiums')
    op.drop_index(op.f('ix_stadiums_id'), table_name='stadiums')
    op.drop_index(op.f('ix_stadiums_city'), table_name='stadiums')
    op.drop_table('stadiums')
    # ### end Alembic commands ###
